import mongoose from "mongoose";
import Video from "./models/Vedio_model.js"
// Connect to MongoDB
mongoose.connect("mongodb://localhost:27017/YoutubeClone")
const db =mongoose.connection
// On successful connection
db.on("open",async ()=>{
    console.log("Connection Succesful")

 try{
 await Video.deleteMany({});

 await Video.insertMany([
    {
      VedioId:  "video01",
      title: "Learn React In 30 Minutes",
      category:"Education",
      thumbnailUrl: "https://img.youtube.com/vi/hQAHSlTtcmY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/hQAHSlTtcmY?autoplay=1&rel=0",
      description: "In this video I will be covering all of the basics of React in only 30 minutes. We will cover create-react-app, components, state, props, rendering, event handling, and so much more. By the end of this video you will have a full understanding of the basics of React, but if you want to take your React knowledge to the next level checkout my full React course linked above for the best React learning experience on the web.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,389,127 views",
      likes: "27k",
      dislikes: "2k",
      comments: [{"commentId": "comment01","userId":"@jardinek2121", "text":"QUICK TIP: Make sure your playback is at least 1.5 times speed, if you want to become fluent in Todo language.","timestamp":"4 years ago"}],
    },
    {
      VedioId:  "video02",
      title: "Raghuvaran B.tech Songs - Luckkanna Mate Nillu - Dhanush, Amala Paul",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/Mm1Zp80gj1Q/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/Mm1Zp80gj1Q?autoplay=1&rel=0",
      description:" Dhanush, Amala Paul, Saranya Ponvannan, Samidrakani, Surabhi, Amitesh & Vivek. This movie Wriiten & Directed by R. Velraj. Produced by Sravanthi Ravi Kishore. Music of the film composed by Anirudh.",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "49,444,993 views",
      likes: "351k",
      dislikes: "3k",
      comments:[{"commentId": "comment02","userId":"@nayakudisanjay9353","text":"National anthem for singles...💘💘💘","timestamp":"6 years ago "}]
    },
    {
      VedioId:  "video03",
      title: "Chirunama Thana Chirunama Full Video Song  Ekkadiki Pothavu Chinnavada Songs Nikhil, Avika Gor",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/6CcOrjc0bJ4/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/6CcOrjc0bJ4?autoplay=1&rel=0",
      description:"Movie: Ekkadiki Pothavu Chinnavada,Cast: Nikhil Siddharth,Hebah Patel, Nandita Swetha,Avika Gor,Raja Ravindra,Director: Vi Anand,Music: Shekar Chandra,Producer:P.VRao",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "27,285,148 views",
      likes: "141k",
      dislikes: "1k",
      comments:[{"commentId": "comment03","userId":"@prashanth394","text":"2021 లో కూడా ఈ సాంగ్ వినేవాళ్ళు ఒక లైక్ వేసుకోండి భయ్యా...... Superb lyrics","timestamp":"4 years ago"}]
    },
    {
      VedioId:  "video04",
      title: "Julayi Latest Telugu Full Length Movie | Allu Arjun, Ileana | 2021 Telugu Movies",
      category:"Movie",
      thumbnailUrl: "https://img.youtube.com/vi/tZquI3a1qZw/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/tZquI3a1qZw?autoplay=1&rel=0",
      description:"Cast: Allu Arjun, Ileana D'Cruz, Sonu Sood, Rajendra Prasad,Director: Trivikram Srinivas,Music: Devi Sri Prasad,Producer: S. Radha Krishna, DVV Danayya",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "14,769,203 views",
      likes: "66k",
      dislikes: "2.5k",
      comments:[{"commentId": "comment04","userId":"@Handcrafts_for_u","text":"10 times kante ekkuva sarlu chusinavallu entha mandi unnaru","timestamp":"6 months ago"}]
    },
    {
      VedioId:  "video05",
      title: "Yentavadu Gaani Latest Telugu Movie Songs - Neekem Kaavaalo Cheppu - Ajith, Anushka",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/3_rMnglt5Vk/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/3_rMnglt5Vk?autoplay=1&rel=0",
      description:"Movie: Yentavadu Gaani,Cast: Ajith, Trisha, Anushka,Director: Gautham Menon, Music: Harris Jayraj, Producer: S.Aishwarya,Release Date: May 22, 2015.",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "35,615,157 views",
      likes: "161k",
      dislikes: "3.5k",
      comments:[{"commentId": "comment05","userId":"@ngracypriyanka8511","text":"I miss you daddy. I love you daddy. Who love there father just like here👇","timestamp":"5 years ago"}]
    },
    {
      VedioId:  "video06",
      title: "Raja Rani Telugu Full Length Movie || Aarya, Nayanthara, Nazriya Nazim, Jai",
      category:"Movie",
      thumbnailUrl: "https://img.youtube.com/vi/qgSpqOHP3H8/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/qgSpqOHP3H8?autoplay=1&rel=0",
      description:"Raja Rani is the story of a newly married couple, Arya & Nayantara who are like Tom and Jerry. Raja Rani is the story of Arya & Nayantara before and after their wedding.",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "44,349,443 views",
      likes: "275k",
      dislikes: "3k",
      comments:[{"commentId": "comment06","userId":"@kpardharam4505","text":"First Half for Girls Side.... Second half for Boys side...and Single's side 💙💙💙😘😘😘 what a movie ..what a Direction.. hattsoff  To the director Attlee sir 🙏💯🔥","timestamp":"5 years ago"}]
    },
    {
      VedioId:  "video07",
      title: "Pokiri Telugu Full HD Movie | 4K | Mahesh Babu, Ileana D'Cruz | 2025 New Telugu Movies",
      category:"Movie",
      thumbnailUrl: "https://img.youtube.com/vi/sIX8ghgD2x8/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/sIX8ghgD2x8?autoplay=1&rel=0",
      description:"Pokiri Telugu Full HD Movie | 4K | Mahesh Babu, Ileana D'Cruz",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "13,048 views",
      likes: "199k",
      dislikes: "2k",
      comments:[{"commentId": "comment07","userId":"@SampathSyndicate","text":"movie audio normal la lekunda pitch change ayindi pettaru 4k ani cheppi cheating chesaru nenu unlike kottina poo","timestamp":"5 years ago"}]
    },
    {
      VedioId:  "video08",
      title: "#S/O Satyamurthy Movie #AlluArjun Very Heart Touching Scenes",
      category:"Movie",
      thumbnailUrl: "https://img.youtube.com/vi/W-KUmkuej4s/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/W-KUmkuej4s?autoplay=1&rel=0",
      description:"What a performance by Allu Arjun and Rao Ramesh, superb acting",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "3,922,881 views",
      likes: "33k",
      dislikes: "1k",
      comments:[{"commentId": "comment08","userId":"@NIRANJANKUMAR-vv5le","text":"Trivikram Dialogues+Allu Arjun Acting+DSP BGM 🔥🔥🔥🔥🔥","timestamp":"2 years ago"}]
    },
    {
      VedioId:  "video09",
      title: "Allu Arjun Most Popular Power Pack Action Scene | Upendra | S/O Satyamurthy Movie",
      category:"Movie",
      thumbnailUrl: "https://img.youtube.com/vi/Tcsg8OIxcRk/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/Tcsg8OIxcRk?autoplay=1&rel=0",
      description:"Uppi acting ,ravishankar voice super combination,love from karnataka because uppi2 fans like here",
      channelId:"@VolgaVideo",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzbGAgSo-J4GABR5lfFYzDMM0JpQ1-niCo5A&s",
      uploader:"Volga Video",
      views: "4,875,898 views",
      likes: "22k",
      dislikes: "1.5k",
      comments:[{"commentId": "comment09","userId":"@pradeepac.b4257","text":"ನಮ್ಮ ಕರ್ನಾಟಕದ ಸ್ಯಾಂಡಲ್ ವುಡ್ ನ ಉಪೇಂದ್ರ ಸರ್ ಅವರ ಆಕ್ಟಿಂಗ್ ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ","timestamp":"6 years ago"}]

    },
    {
      VedioId:  "video10",
      title: "Magadheera Movie Action Scene | Ram Charan, Kajal Aggarwal | Sunil, DevGill, SriHari | SS Rajamouli",
      category:"Movie",
      thumbnailUrl: "https://img.youtube.com/vi/A2hTZDss95Y/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/A2hTZDss95Y?autoplay=1&rel=0",
      description:"Magadheera is our Telugu-language fantasy action film directed by S. S. Rajamouli and produced by Allu Aravind under Geetha Arts, on a story by V. Vijayendra Prasad. The film stars Ram Charan, Srihari, Kajal Aggarwal and Dev Gill in lead roles. Music composed by MM Keeravani. Cinematography by K. K. Senthil Kumar. Edited by Kotagiri Venkateswara Rao.",
      channelId:"@geethaarts",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiftZuFII19ZkgXtdLgPH3n97KAXfA7tpLSQ&s",
      uploader:"Geetha Arts",
      views: "1,501,429 views",
      likes: "11k",
      dislikes: "2k",
      comments:[{"commentId": "comment10","userId":"@deepakdkdr7169","text":"This scene in the movie is carried by MM.KEERAVANI SIR BACKGROUND MUSIC 🎶 🎵 ❤❤","timestamp":"5 years ago"}]
    },
    {
      VedioId:  "video11",
      title: "Magadheera Telugu Full Movie | 4K | Dolby Audio | Ram Charan, Kajal Aggarwal, Dev Gill | SSRajamouli",
      category:"Movie",
      thumbnailUrl: "https://img.youtube.com/vi/1DIrsAOkx1c/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/1DIrsAOkx1c?autoplay=1&rel=0",
      description:"Magadheera is our Telugu-language fantasy action film directed by S. S. Rajamouli and produced by Allu Aravind under Geetha Arts, on a story by V. Vijayendra Prasad. The film stars Ram Charan, Srihari, Kajal Aggarwal and Dev Gill in lead roles. Music composed by MM Keeravani. Cinematography by K. K. Senthil Kumar. Edited by Kotagiri Venkateswara Rao.",
      channelId:"@geethaarts",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiftZuFII19ZkgXtdLgPH3n97KAXfA7tpLSQ&s",
      uploader:"Geetha Arts",
      views: "54216,352 views",
      likes: "55k",
      dislikes: "2k",
      comments:[{"commentId": "comment11","userId":"@RavikumarJSP","text":"Ee cenima chusi baytiki vellaleka again theatre ki velli aa sound vine vanni ","timestamp":"1 year ago"}]
    },
    {
      VedioId:  "video12",
      title: "Nuvvostanante Nenoddantana Video Songs | Aakasam Thakela Video Song | Siddharth",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/81fRS0FildI/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/81fRS0FildI?autoplay=1&rel=0",
      description:"Siri (Trisha) & Sivarama Krishna (Srihari) are orphans. Their rich father leaves their mother for another woman. And so their mother dies in distress. With this kind of troubled childhood, Sivarama Krishna (Srihari) takes care of his little sister Siri and makes sure that she gets all the brotherly love she needs",
      channelId:"@SriBalajiMusic",
      channelLogo:"https://yt3.googleusercontent.com/OEFzd658gBRbDAMLHMA2uPcB5Oy4j8w30cgwfMz51RDnbSA5U35or0NVAbgeoVAr-cBwpkQvug=s900-c-k-c0x00ffffff-no-rj",
      uploader:"Sri Balaji Music",
      views: "56,468,833 views",
      likes: "195k",
      dislikes: "2k",
      comments:[{"commentId": "comment12","userId":"@ravib1082","text":"Thrisha's expressions in this song is priceless. Most underrated beauty.","timestamp":"4 years ago"}]

    },
    {
      VedioId:  "video13",
      title: "Oye Video Songs | Oye Oye (Title Song) Video Song | Siddharth, Shamili | Sri Balaji Video",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/nmAI4ut_Yro/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/nmAI4ut_Yro?autoplay=1&rel=0",
      description:"Uday (Siddharth) is a rich and spoilt brat who believes in short term pleasures. Sandhya (Shamili) is a loner who lives on her own. She is a responsible girl with long term plans and strict principles. Uday falls in love with Sandhya at the very first sight. And she joins her place as a paying guest.",
      channelId:"@SriBalajiMusic",
      channelLogo:"https://yt3.googleusercontent.com/OEFzd658gBRbDAMLHMA2uPcB5Oy4j8w30cgwfMz51RDnbSA5U35or0NVAbgeoVAr-cBwpkQvug=s900-c-k-c0x00ffffff-no-rj",
      uploader:"Sri Balaji Music",
      views: "25,866,432 views",
      likes: "95k",
      dislikes: "2k",
      comments:[{"commentId": "comment13","userId":"@vishiyas","text":"Got a chance to see the live performance of this Song at a Vizag with a live band. The drum work is exceptional, I mean seriously good stuff and real talent. Intricate notes and many types of drums were used to get the song right.","timestamp":'4 months ago'}]
    },
    {
      VedioId:  "video14",
      title: "Bala Tripuramani - Full Video | Brahmotsavam | Mahesh Babu | Kajal Aggarwal | Mickey J Meyer",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/zq55GTBp8ho/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/zq55GTBp8ho?autoplay=1&rel=0",
      description:"Presenting the full video of Bala Tripuramani sung by Rahul Nambiar. ",
      channelId:"@zeemusicsouth",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6C9iS5H7mVslUBcWSX-Sdnh3E16ws6V19ROEfeQtjH9rEQcudgFt_jTptPpZfGnpgXo&usqp=CAU",
      uploader:"Zee Music South",
      views: "7,856,764 views",
      likes: "93k",
      dislikes: "3k",
      comments:[{"commentId": "comment14","userId":"@NameisChakri","text":"Kajal is like a Princess who came from wonderland ❤","timestamp":"4 months ago"}]
    },
    {
      VedioId:  "video15",
      title: "என்னை சொந்தம் Ennai Sondham - Bhediya | Varun Dhawan, Kriti Sanon | Sachin-Jigar",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/kZHStsm4jSY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/kZHStsm4jSY?autoplay=1&rel=0",
      description:"Starring: Varun Dhawan, Kriti Sanon, Deepak Dobriyal, Abhishek Banerjee, Paalin Kabak ",
      channelId:"@zeemusicsouth",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6C9iS5H7mVslUBcWSX-Sdnh3E16ws6V19ROEfeQtjH9rEQcudgFt_jTptPpZfGnpgXo&usqp=CAU",
      uploader:"Zee Music South",
      views: "3,850 views",
      likes: "933k",
      dislikes: "13k",
      comments:[{"commentId": "comment15","userId":"@avenjustortamil8291","text":"Dai Yara neenga enga irundhu da vandhu irukinga Unga YouTube channel la indha Movie oda all Songs Tamil Version Available ah irukku edhuku da original irukkum bodhu thirumbo Release pandinga","timestamp":"2 years ago"}]

    },
    {
      VedioId:  "video16",
      title: "நான் மெல்ல மெல்ல காதலில் Naan Mella Mella Kaadhalil | Sidharth Malhotra,Neha Sharma | Denniz Joseph",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/rDlMFLi1F2M/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/rDlMFLi1F2M?autoplay=1&rel=0",
      description:"Song: Naan Mella Mella Kaadhalil Singer: Denniz JosephTamil Writer: Rupendar KiranMixing: Pankaj Rajpoot",
      channelId:"@zeemusicsouth",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6C9iS5H7mVslUBcWSX-Sdnh3E16ws6V19ROEfeQtjH9rEQcudgFt_jTptPpZfGnpgXo&usqp=CAU",
      uploader:"Zee Music South",
      views: "2,894 views",
      likes: "933k",
      dislikes: "13k",
      comments:[{"commentId": "comment16","userId":"@NEHADEVASIA","text":"Amazing job... The try to do in Tamil was really good... The voice is nice...","timestamp":"2 months ago"}]

    },
    {
      VedioId:  "video17",
      title: "Naa Kosam - Full Video | Bangarraju | Naga Chaitanya | Krithi Shetty | Anup Rubens",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/BDgK6E-2LyM/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/BDgK6E-2LyM?autoplay=1&rel=0",
      description:"Akkineni Nagarjuna, Akkineni Naga Chaitanya, Ramya Krishna, Krithi Shetty, Rao Ramesh, Brahmaji, Vennela Kishore, Jhansi, Anitha Chowdhary, Rohini, Praveen, Padma Soorya & Ranjith",
      channelId:"@zeemusicsouth",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6C9iS5H7mVslUBcWSX-Sdnh3E16ws6V19ROEfeQtjH9rEQcudgFt_jTptPpZfGnpgXo&usqp=CAU",
      uploader:"Zee Music South",
      views: "2,894 views",
      likes: "933k",
      dislikes: "13k",
      comments:[{"commentId": "comment17","userId":"@sanjukumar580","text":"ఈ పాట అంటే ఎంతమందికి ఇష్టం...😍🔥ఈ పాట వింటున్న సేపు ఏదో లోకానికి వెళ్ళి పోయినట్టు ఉంది అనూప్ రుబీన్స్  అద్భుతమైన మ్యూజిక్ ఇచ్చాడు సిద్ శ్రీరామ్ పాటకి ప్రాణం పోశాడు సూపర్👌👌","timestamp":"3 years ago"}]
    },
    {
      VedioId:  "video18",
      title: "Spirit Of Jersey - Full Video | Jersey | Nani, Shraddha Srinath | Anirudh Ravichander",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/_xuI60USDjw/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/_xuI60USDjw?autoplay=1&rel=0",
      description:"Presenting the full video of Spirit Of Jersey sung by Kaala Bhairava.",
      channelId:"@zeemusicsouth",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6C9iS5H7mVslUBcWSX-Sdnh3E16ws6V19ROEfeQtjH9rEQcudgFt_jTptPpZfGnpgXo&usqp=CAU",
      uploader:"Zee Music South",
      views: "15,462,388 views",
      likes: "223k",
      dislikes: "3k",
      comments:[{"commentId": "comment18","userId":"@sudheemadhav","text":"Idk when iam listening to this song I remember virat kohli nd his efforts for winning Every match for India 😊😊","timestamp":"1 day ago"}]

    },
    {
      VedioId:  "video19",
      title: "Run - Full Video | Bruce Lee The Fighter | Ram Charan | Sai Sharan & Nivaz",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/OpjbJXciXwU/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/OpjbJXciXwU?autoplay=1&rel=0",
      description:"Presenting the full video of Run from Bruce Lee The Fighter featuring Ram Charan. ",
      channelId:"@zeemusicsouth",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6C9iS5H7mVslUBcWSX-Sdnh3E16ws6V19ROEfeQtjH9rEQcudgFt_jTptPpZfGnpgXo&usqp=CAU",
      uploader:"Zee Music South",
      views: "15,462,388 views",
      likes: "225k",
      dislikes: "9k",
      comments:[{"commentId": "comment19","userId":"@akhilabhoopathi9456","text":"Ramcharan ki avaru poti raru raleru. He z king of dance","timestamp":"4 years ago"}]
    },
    {
      VedioId:  "video20",
      title: "Gabbar Singh Songs | Pillaa Nuvveleni Jeevitham Full Video Song | Latest Telugu Superhits",
      category:"Music",
      thumbnailUrl: "https://img.youtube.com/vi/2Uc9Pw9uS9k/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/2Uc9Pw9uS9k?autoplay=1&rel=0",
      description:"Watch & Enjoy Gabbar Singh Latest Telugu Movie Songs, Starring Pawan Kalyan, Shruti Hassan & others, Music Composed by Devi Sri Prasad, Directed by Harish Shankar S. #GabbarSingh #PawanKalyan #DeviSriPrasad",
      channelId:"@SriBalajiMovies",
      channelLogo:"https://yt3.googleusercontent.com/OEFzd658gBRbDAMLHMA2uPcB5Oy4j8w30cgwfMz51RDnbSA5U35or0NVAbgeoVAr-cBwpkQvug=s900-c-k-c0x00ffffff-no-rj",
      uploader:"SriBalajiMovies",
      views: "15,776,441 views",
      likes: "255k",
      dislikes: "6k",
      comments:[{"commentId": "comment20","userId":"@murughanandhanv.m6309","text":"Welcome to Tamilnadu Pawan Kalyan 👌👌💯👑👑 DSP music king 👑💯","timestamp":"4 months ago"}]
    },
    {
      VedioId:  "video21",
      title: "How To Debug React Apps Like A Senior Developer",
      category:"Education",
      thumbnailUrl: "https://img.youtube.com/vi/l8knG0BPr-o/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/l8knG0BPr-o?autoplay=1&rel=0",
      description:"Debugging React apps can be a difficult process if you don’t have the right tools. That is why in this video I will show you what tools you need to debug React apps like a professional and also how to properly use those tools like a senior developer.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,389,127 views",
      likes: "37k",
      dislikes: "6k",
      comments: [{"commentId": "comment21","userId":"@jardinek2121", "text":"Ironically, the more seniorI get (20 years) the less I feel a need for these things. A few strategically placed console logs tend to be sufficient for most bugs. Impressive though!","timestamp":"4 years ago"}],
    },
    {
      VedioId:  "video22",
      title: "CSS Finally Has if() Statements (but I don’t think I will use them)",
      category:"Education",
      thumbnailUrl: "https://img.youtube.com/vi/mvgY3GvcSCo/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/mvgY3GvcSCo?autoplay=1&rel=0",
      description:"Having the ability to do if statements in CSS would have been a dream of mine years ago, and it is finally a reality. Surprisingly, though, I don’t think I will end up using them much (if at all). In this video I will show you how these if statements work as well as talk about why I don’t see much use for them.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,389,197 views",
      likes: "33k",
      dislikes: "4k",
      comments: [{"commentId": "comment22","userId":"@DEVDerr", "text":"We got CSS becoming a programming language before GTA 6","timestamp":"8 years ago"}],
    },
    {
      VedioId:  "video23",
      title: "Next.js Finally Fixed Caching",
      category:"Education",
      thumbnailUrl: "https://img.youtube.com/vi/nHnw3pusFXw/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/nHnw3pusFXw?autoplay=1&rel=0",
      description:"Caching has been one of the worst parts of Next.js for years, but with the new DynamicIO and “use cache” features I think they have finally nailed caching.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,349,197 views",
      likes: "13k",
      dislikes: "1k",
      comments: [{"commentId": "comment23","userId":"@williandamascenomusic", "text":"I used to love NextJS, nowdays I'm happy using Laravel","timestamp":"5 months ago"}],
    },
    {
      VedioId:  "video24",
      title: "How To Handle CSS Colors Like A Senior Dev",
      category:"Education",
      thumbnailUrl: "https://img.youtube.com/vi/Acs-tJV4iAo/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/Acs-tJV4iAo?autoplay=1&rel=0",
      description:"Colors in CSS seem rather simple at first, but they are such an incredibly deep concept. Things like relative colors, color mixing, color spaces/gamuts, and so much more mean you can do so much with color in CSS",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,349,397 views",
      likes: "63k",
      dislikes: "2k",
      comments: [{"commentId": "comment24","userId":"@MuhammadAlam-ne9cf", "text":"just the first 3 minutes alone are worth the price of admission. but the entire video is a wealth of knowledge thanks kyle","timestamp":"5 months ago"}],
    },
    {
      VedioId:  "video25",
      title: "Am I Good Enough To Solve These CSS Battles?",
      category:"Education",
       thumbnailUrl: "https://img.youtube.com/vi/eED9tbBVM4o/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/eED9tbBVM4o?autoplay=1&rel=0",
      description:"In this video I attempt to solve multiple CSS Battles live. This is a great video for seeing my thought process when tackling complex CSS problems.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,349,97 views",
      likes: "43k",
      dislikes: "2k",
      comments: [{"commentId": "comment25","userId":"@MuhammadAlam-ne9cf", "text":"just the first 3 minutes alone are worth the price of admission. but the entire video is a wealth of knowledge thanks kyle","timestamp":"5 months ago"}],
    },
    {
      VedioId:  "video26",
      title: "How To Setup Fingerprint Auth In JavaScript",
      category:"JavaScript",
      thumbnailUrl: "https://img.youtube.com/vi/viZs1iVsLpA/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/viZs1iVsLpA?autoplay=1&rel=0",
      description:"Authentication is a difficult topic especially when dealing with biometric auth and passkeys. That is until now. In this video I will explain how you can use webauthn APIs to easily create fingerprint, biometric, and passkey based authentication without needing to pay for any third party providers",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,349,987 views",
      likes: "23k",
      dislikes: "5k",
      comments: [{"commentId": "comment26","userId":"@EthioPodcaster", "text":"Very cool that you created this video, the explanation of the process is spot on! It would be nice to have also a variation of this implementation where a user can use multiple KeyPasses for a single user account. Thank you! 🙏","timestamp":"5 months ago"}],
    },
     {
      VedioId:  "video27",
      title: "Next.js 15 Ruins Caching Even More",
      category:"JavaScript",
      thumbnailUrl: "https://img.youtube.com/vi/3RyguimNe8s/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/3RyguimNe8s?autoplay=1&rel=0",
      description:"Caching in Next.js has been a sore subject for a couple years now, but Next.js 15 is here to fix all our caching problems. Well not quite. In reality it fixes a few problems",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,34,987 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment27","userId":"@incrypted607", "text":"You definitely are one of the people who understand how Nextjs caching mechanisms work.","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video28",
      title: "8 NEW JavaScript 2024 Features",
      category:"JavaScript",
     thumbnailUrl: "https://img.youtube.com/vi/duNEnLUxie8/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/duNEnLUxie8?autoplay=1&rel=0",
      description:"JavaScript is constantly evolving with new features being added yearly. In this video I am going through 8 new features that are being added to JavaScript in 2024 or will hopefully be added in 2024. Some of these features are real game changers.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,34,957 views",
      likes: "22k",
      dislikes: "1k",
      comments: [{"commentId": "comment28","userId":"@MaksymCzech", "text":"This was a good video. Decorators looks interesting and I am pumped for Temporal","timestamp":"12 months ago"}],
    },
    {
      VedioId:  "video29",
      title: "How To Create/Use Functions - JavaScript Essentials",
      category:"JavaScript",
      thumbnailUrl: "https://img.youtube.com/vi/FOD408a0EzU/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/FOD408a0EzU?autoplay=1&rel=0",
      description:"Functions are one of the most important things to understand in JavaScript since you will use them everywhere in your code. They are arguably more important than learning how to create a variable since they are that core to how JavaScript works",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,34,57 views",
      likes: "22k",
      dislikes: "1k",
      comments: [{"commentId": "comment29","userId":"@wolfhaize", "text":"*me who has been writing JavaScript for 2+ years*: ah yes, interesting","timestamp":"12 months ago"}],
    },
    {
      VedioId:  "video30",
      title: "How To Learn JavaScript In 2023 - From Zero To Mid-Level Developer",
      category:"JavaScript",
      thumbnailUrl: "https://img.youtube.com/vi/7L2RLBmEJmE/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/7L2RLBmEJmE?autoplay=1&rel=0",
      description:"JavaScript is complex and difficult to learn, but it doesn’t have to be. In this video I share with you every single JS topic you need to learn in order to master JavaScript.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,34,87 views",
      likes: "12k",
      dislikes: "6k",
      comments: [{"commentId": "comment30","userId":"@mistn", "text":"*me who has been writing JavaScript for 2+ years*: ah yes, interesting","timestamp":"12 months ago"}],
    },
    {
      VedioId:  "video31",
      title: "How To Draw CSS Emoji Illustrations",
      category:"CSS",
      thumbnailUrl: "https://img.youtube.com/vi/P3LXA6duP5g/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/P3LXA6duP5g?autoplay=1&rel=0",
      description:"Creating the same web design over and over again can get really boring. I mean there are only so many times you can create a button before wanting to throw your keyboard out a window.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,346,87 views",
      likes: "42k",
      dislikes: "6k",
      comments: [{"commentId": "comment31","userId":"@ScileSc", "text":"It always amazes me how you explain the basics of web development like html and css as you go along every video. Just long enough that beginners can follow and quick enough that it´s not getting boring for experienced people.","timestamp":"12 months ago"}],
    },
    {
      VedioId:  "video32",
      title: "20 NEW CSS Features You Need To Know In 2025",
      category:"CSS",
      thumbnailUrl: "https://img.youtube.com/vi/VA975GOUFmM/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/VA975GOUFmM?autoplay=1&rel=0",
      description:"In this video I will show you my 20 favorite new CSS features that you should be using in 2025 and beyond.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,346,82 views",
      likes: "42k",
      dislikes: "6k",
      comments: [{"commentId": "comment32","userId":"@ScileSc", "text":"It always amazes me how you explain the basics of web development like html and css as you go along every video. Just long enough that beginners can follow and quick enough that it´s not getting boring for experienced people.","timestamp":"12 months ago"}],
    },
     {
      VedioId:  "video33",
      title: "This CSS Property Replaces Hundreds of Lines of Code",
      category:"CSS",
      thumbnailUrl: "https://img.youtube.com/vi/ElELqkwzcYM/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/ElELqkwzcYM?autoplay=1&rel=0",
      description:"The CSS field-sizing property is an amazing new CSS property that makes creating auto-sizing text boxes incredibly easy. No longer do you need JavaScript for simple auto expanding text boxes..",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,346,8 views",
      likes: "42k",
      dislikes: "6k",
      comments: [{"commentId": "comment33","userId":"@ScileSc", "text":"It always amazes me how you explain the basics of web development like html and css as you go along every video. Just long enough that beginners can follow and quick enough that it´s not getting boring for experienced people.","timestamp":"12 months ago"}],
    },
     {
      VedioId:  "video34",
      title: "How To Master CSS in 1 Month!",
      category:"CSS",
      thumbnailUrl: "https://img.youtube.com/vi/kPOjdPlhWmA/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/kPOjdPlhWmA?autoplay=1&rel=0",
      description:"The CSS field-sizing property is an amazing new CSS property that makes creating auto-sizing text boxes incredibly easy. No longer do you need JavaScript for simple auto expanding text boxes..",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,36,8 views",
      likes: "42k",
      dislikes: "6k",
      comments: [{"commentId": "comment34","userId":"@Abulucu-g6p", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
    {
      VedioId:  "video35",
      title: "@property Is One Of The Coolest New CSS Features",
      category:"CSS",
      thumbnailUrl: "https://img.youtube.com/vi/sd34qnxSeoU/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/sd34qnxSeoU?autoplay=1&rel=0",
      description:"@property is one of the coolest CSS features that has been released in the last few years. I think it has the potential to be as revolutionary as grid and flexbox, but there are a few tooling changes that need to happen for that first.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,36,876 views",
      likes: "32k",
      dislikes: "1k",
      comments: [{"commentId": "comment35","userId":"@GilGoldshlager", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
    {
      VedioId:  "video36",
      title: "Before Your Next Interview Watch This",
      category:"Data Structures",
      thumbnailUrl: "https://img.youtube.com/vi/RcvQagxK_9w/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/RcvQagxK_9w?autoplay=1&rel=0",
      description:"There are tons of data structures and algorithms that you can learn but you do not need to know them all. In this video I will share with you the 10 most important data structures and algorithms that you need to know in order to pass your next technical interview.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,676,876 views",
      likes: "32k",
      dislikes: "1k",
      comments: [{"commentId": "comment36","userId":"@GilGoldshlager", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
    {
      VedioId:  "video37",
      title: "How To Solve Algorithms - Adding Linked Lists",
      category:"Data Structures",
      thumbnailUrl: "https://img.youtube.com/vi/cEGx1zqD78Y/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/cEGx1zqD78Y?autoplay=1&rel=0",
      description:"Algorithms are difficult to understand, but absolutely crucial for landing a job. In this video I will be explaining how to add two linked lists together in depth. This problem is great since it focuses on problem solving skills as opposed to one off memorization.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,676,87 views",
      likes: "3k",
      dislikes: "1k",
      comments: [{"commentId": "comment37","userId":"@GilGoldshlager", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
    {
      VedioId:  "video38",
      title: "Learn Big O Notation In 12 Minutes",
      category:"Data Structures",
      thumbnailUrl: "https://img.youtube.com/vi/itn09C2ZB9Y/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/itn09C2ZB9Y?autoplay=1&rel=0",
      description:"Algorithms are difficult to understand, but absolutely crucial for landing a job. In this video I will be explaining how to add two linked lists together in depth. This problem is great since it focuses on problem solving skills as opposed to one off memorization.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,676,87 views",
      likes: "3k",
      dislikes: "1k",
      comments: [{"commentId": "comment38","userId":"@GilGoldshlager", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
     {
      VedioId:  "video39",
      title: "5 Must Know Sorting Algorithms Explained and Visualized",
      category:"Data Structures",
      thumbnailUrl: "https://img.youtube.com/vi/W35KhZq2xFQ/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/W35KhZq2xFQ?autoplay=1&rel=0",
      description:"Sorting algorithms are pretty complex to understand when dealing with big O notation). In this video I will show you the 5 most common sorting algorithms, talk about big O notation for them, and visually show you how they work alongside fully working code examples.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,676,67 views",
      likes: "3k",
      dislikes: "1k",
      comments: [{"commentId": "comment39","userId":"@GilGoldshlager", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
    {
      VedioId:  "video40",
      title: "How To Solve Algorithms - Longest Common Prefix",
      category:"Data Structures",
      thumbnailUrl: "https://img.youtube.com/vi/gJOgI8TpSgc/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/gJOgI8TpSgc?autoplay=1&rel=0",
      description:"Algorithms are difficult to understand, but absolutely crucial for landing a job. In this video I will be explaining the longest common prefix algorithm in depth. I will cover both of the most common approaches to the algorithm and comparing them",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,67,67 views",
      likes: "3k",
      dislikes: "1k",
      comments: [{"commentId": "comment40","userId":"@GilGoldshlager", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
     {
      VedioId:  "video41",
      title: "#0 Python for Beginners | Programming Tutorial",
      category:"Python",
      thumbnailUrl: "https://img.youtube.com/vi/QXeEoD0pB3E/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/QXeEoD0pB3E?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Python is one of the best programming language and easy to learn Python is used in Machine Learning, Data Science, Big Data, Web Development, Scripting.",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,67,67 views",
      likes: "3k",
      dislikes: "1k",
      comments: [{"commentId": "comment41","userId":"@nicoles_handle", "text":"the only pre-requisite here is your time what a lad. people like you are what make youtube great, thank you!","timestamp":"1 year ago"}],
    },
    {
      VedioId:  "video42",
      title: "#4 Python Tutorial for Beginners | Variables in Python",
      category:"Python",
      thumbnailUrl: "https://img.youtube.com/vi/TqPzwenhMj0/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/TqPzwenhMj0?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"In this lecture we are discussing variable in python: Variable: It is a container where we can put our value",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,67 views",
      likes: "2k",
      dislikes: "1k",
      comments: [{"commentId": "comment42","userId":"@motheakanksha6082", "text":"Making such a effort  without expecting anything and explaining with lots of clarity is really awesome,and huge respect to you","timestamp":"1 year ago"}],
    },
    {
      VedioId:  "video43",
      title: "#10 Python Tutorial for Beginners | Data Types in Python",
      category:"Python",
      thumbnailUrl: "https://img.youtube.com/vi/gCCVsvgR2KU/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/gCCVsvgR2KU?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Python has several built-in data types. Here are some of the most common ones:",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,67 views",
      likes: "2k",
      dislikes: "1k",
      comments: [{"commentId": "comment43","userId":"@Maheshwari_Ravi", "text":"Hi Navin, could you please also provide exercise sheets so that we can get good practice on each topic as soon as a video is finished.","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video44",
      title: "#12 Python Tutorial for Beginners | Number System Conversion in Python",
      category:"Python",
      thumbnailUrl: "https://img.youtube.com/vi/AWAjbtWBzGs/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/AWAjbtWBzGs?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"In this lecture we are discussing about Number System and its conversion:",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,67 views",
      likes: "2k",
      dislikes: "1k",
      comments: [{"commentId": "comment44","userId":"@Maheshwari_Ravi", "text":"Hi Navin, could you please also provide exercise sheets so that we can get good practice on each topic as soon as a video is finished.","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video45",
      title: "#15 Python Tutorial for Beginners | Import Math Functions in Python",
      category:"Python",
      thumbnailUrl: "https://img.youtube.com/vi/EkYrfV7M1ks/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/EkYrfV7M1ks?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"In this lecture we are discussing about math function: ",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,687 views",
      likes: "2k",
      dislikes: "2k",
      comments: [{"commentId": "comment45","userId":"@Maheshwari_Ravi", "text":"Hi Navin, could you please also provide exercise sheets so that we can get good practice on each topic as soon as a video is finished.","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video46",
      title: "#1 Java Introduction",
      category:"Java",
      thumbnailUrl: "https://img.youtube.com/vi/bm0OyhwFDuY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/bm0OyhwFDuY?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Java Full Course Learn Java Fundamentals, OOP, Interface, exception handling, collection api, threads",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,687 views",
      likes: "2k",
      dislikes: "2k",
      comments: [{"commentId": "comment46","userId":"@Pratyush.K.R", "text":"I was preparing for my first job interviews from this channel and now after 7 years again watching this playlist.  It feels so satisfying. I'll watch every video of this series","timestamp":"3 year ago"}],
    },
     {
      VedioId:  "video47",
      title: "#2 Java Development Kit (JDK) Setup",
      category:"Java",
      thumbnailUrl: "https://img.youtube.com/vi/WRISYpKhIrc/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/WRISYpKhIrc?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"In this lecture we are discussing about setup and tools required:",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,627 views",
      likes: "2k",
      dislikes: "2k",
      comments: [{"commentId": "comment47","userId":"@Pratyush.K.R", "text":"I was preparing for my first job interviews from this channel and now after 7 years again watching this playlist.  It feels so satisfying. I'll watch every video of this series","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video48",
      title: "#5 Variables in Java",
      category:"Java",
      thumbnailUrl: "https://img.youtube.com/vi/9RCuKrze_-k/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/9RCuKrze_-k?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Variable is used to store the data temporarily while processing.",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,62 views",
      likes: "23k",
      dislikes: "2k",
      comments: [{"commentId": "comment48","userId":"@Pratyush.K.R", "text":"I was preparing for my first job interviews from this channel and now after 7 years again watching this playlist.  It feels so satisfying. I'll watch every video of this series","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video49",
      title: "#8 Type Conversion in Java",
      category:"Java",
      thumbnailUrl: "https://img.youtube.com/vi/CPk8pffKV64/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/CPk8pffKV64?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"In this lecture we are discussing:1)What is type conversion or type casting ?2)Different ways to casting? a)implicit type casting or automatic type casting b)explicit type casting",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,62 views",
      likes: "23k",
      dislikes: "2k",
      comments: [{"commentId": "comment49","userId":"@Pratyush.K.R", "text":"I was preparing for my first job interviews from this channel and now after 7 years again watching this playlist.  It feels so satisfying. I'll watch every video of this series","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video50",
      title: "#10 Relational Operators in Java",
      category:"Java",
      thumbnailUrl: "https://img.youtube.com/vi/TEJpeRI_NEo/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/TEJpeRI_NEo?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Relational operators are used where we need to compare things.",
      channelId: "@Telusko",
      channelLogo:"https://yt3.googleusercontent.com/0nsZM3NF0C9bFr2IFXicMJ1w82ldRaZvGKFnezBe2lpW7F9gI92FaLubcTghnNNt4Ld8DfRvEMo=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Telusko",
      views: "1,23,362 views",
      likes: "23k",
      dislikes: "2k",
      comments: [{"commentId": "comment50","userId":"@Pratyush.K.R", "text":"I was preparing for my first job interviews from this channel and now after 7 years again watching this playlist.  It feels so satisfying. I'll watch every video of this series","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video51",
      title: "🔥TCS FREE NQT, Capital One, Impetus Biggest Test | Exam Pattern | Off Campus Drive 2025-2021 BATCH",
      category:"Recruitment",
      thumbnailUrl: "https://img.youtube.com/vi/Wya1izGfSRk/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/Wya1izGfSRk?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Hello everyone this video is all about Current Hiring Updates.",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,23,362 views",
      likes: "23k",
      dislikes: "2k",
      comments: [{"commentId": "comment51","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
     {
      VedioId:  "video52",
      title: "5 Biggest Test Update | Zeta, SDET, Positka, Amazon, HCLTech | BATCH: 2022-2025 |Test Pattern",
      category:"Recruitment",
      thumbnailUrl: "https://img.youtube.com/vi/Dp8QJiJmFrk/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/Dp8QJiJmFrk?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"✅Join Jobs & Updates Official Whatsapp Group: All Batch",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,23,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment52","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video53",
      title: "Amazon SDE-1 Hiring Process 2025 | Amazon Hiring 2025, 2024 BATCH |Amazon SDE-1 Interview Experience",
      category:"Recruitment",
      thumbnailUrl: "https://img.youtube.com/vi/Q2fKevr_GX8/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/Q2fKevr_GX8?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"✅Join Jobs & Updates Official Whatsapp Group: All Batch",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,27,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment53","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video54",
      title: "🔥Accenture Packaged Application Hiring | Careers Hiring Out | BATCH: 2021-2024 | PADA, SASA 2025?",
      category:"Recruitment",
      thumbnailUrl: "https://img.youtube.com/vi/wAL2xzqsjhM/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/wAL2xzqsjhM?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"✅Join Jobs & Updates Official Whatsapp Group: All Batch",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,27,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment54","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video55",
      title: "🔥DXC, Infosys Analyst Hiring Announced | Off Campus Drive 2025, 2024, 2023, 2022, 2021 BATCH",
      category:"Recruitment",
      thumbnailUrl: "https://img.youtube.com/vi/n0-CXY8ZbLU/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/n0-CXY8ZbLU?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"✅Join Jobs & Updates Official Whatsapp Group: All Batch",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,27,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment55","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video56",
      title: "Back to Back Comedy Scenes 😍🤣| Kick | Ravi Teja | Brahmanandam | Ilena | Ali | Telugu Comedy Scene",
      category:"Comedy Scenes",
      thumbnailUrl: "https://img.youtube.com/vi/oMV4zNzcdWE/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/oMV4zNzcdWE?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Kick is a 2009 Indian Telugu-language action comedy film directed by Surender Reddy from a story by Vakkantham Vamsi. The film stars Ravi Teja, Ileana, and Shaam while Brahmanandam plays a supporting role.",
      channelId: "@geminicomedy",
      channelLogo:"https://upload.wikimedia.org/wikipedia/commons/1/11/Gemini_Comedy_Logo.png",
      uploader: "Gemini Comedy",
      views: "1,27,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment56","userId":"@Moka138", "text":"Super Comedy Brahmi And Ravi Teja 😂😊","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video57",
      title: "Edurintelo Undavalacina Ammayi Ekkada Enduku Undi?|Kick 2|Ravi Teja|Brahmanandam|Telugu Comedy scene",
      category:"Comedy Scenes",
      thumbnailUrl: "https://img.youtube.com/vi/7B2hUsV3p2A/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/7B2hUsV3p2A?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Kick is a 2009 Indian Telugu-language action comedy film directed by Surender Reddy from a story by Vakkantham Vamsi. The film stars Ravi Teja, Ileana, and Shaam while Brahmanandam plays a supporting role.",
      channelId: "@geminicomedy",
      channelLogo:"https://upload.wikimedia.org/wikipedia/commons/1/11/Gemini_Comedy_Logo.png",
      uploader: "Gemini Comedy",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment57","userId":"@Moka138", "text":"Super Comedy Brahmi And Ravi Teja 😂😊","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video58",
      title: "Venumadhav & Shakuntala Non Stop Hilarious Scene 🤣 | Lakshmi | Venkatesh | Nayanthara |Telugu Comedy",
      category:"Comedy Scenes",
      thumbnailUrl: "https://img.youtube.com/vi/3HUKzLIoZnw/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/3HUKzLIoZnw?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Kick is a 2009 Indian Telugu-language action comedy film directed by Surender Reddy from a story by Vakkantham Vamsi. The film stars Ravi Teja, Ileana, and Shaam while Brahmanandam plays a supporting role.",
      channelId: "@geminicomedy",
      channelLogo:"https://upload.wikimedia.org/wikipedia/commons/1/11/Gemini_Comedy_Logo.png",
      uploader: "Gemini Comedy",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment58","userId":"@0000099999ful", "text":"Tiger  comedy  steel  plates tho  inka  brathike  undi  venu maadhav  never  dies  evergreen  😂","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video59",
      title: "Shankar Dada Zindabad Back to back Comedy Scenes 🤣| Chiranjeevi | Telugu Comedy scene",
      category:"Comedy Scenes",
      thumbnailUrl: "https://img.youtube.com/vi/HQr8S8LTggE/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/HQr8S8LTggE?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Explore the official Gemini Comedy channel on YouTube🥳 ! Enjoy Movie Clips , Comedy Scenes, Best scenes, Shorts and more. Subscribe for a cinematic journey into the vibrant world of Telugu cinema!",
      channelId: "@geminicomedy",
      channelLogo:"https://upload.wikimedia.org/wikipedia/commons/1/11/Gemini_Comedy_Logo.png",
      uploader: "Gemini Comedy",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment59","userId":"@0000099999ful", "text":"Tiger  comedy  steel  plates tho  inka  brathike  undi  venu maadhav  never  dies  evergreen  😂","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video60",
      title: "Ultimate Combo Nagarjuna & Brahmanandam 😍| Soggade Chinni Nayana |Ramya Krishnan|Telugu Comedy scene",
      category:"Comedy Scenes",
      thumbnailUrl: "https://img.youtube.com/vi/SA96AJ-Wv8Q/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/SA96AJ-Wv8Q?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Explore the official Gemini Comedy channel on YouTube🥳 ! Enjoy Movie Clips , Comedy Scenes, Best scenes, Shorts and more. Subscribe for a cinematic journey into the vibrant world of Telugu cinema!",
      channelId: "@geminicomedy",
      channelLogo:"https://upload.wikimedia.org/wikipedia/commons/1/11/Gemini_Comedy_Logo.png",
      uploader: "Gemini Comedy",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment60","userId":"@0000099999ful", "text":"Tiger  comedy  steel  plates tho  inka  brathike  undi  venu maadhav  never  dies  evergreen  😂","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video61",
      title: "Indigo Biggest Hiring 2025/2024/2023 | TCS Final Result , Joining | TCS Next Exam",
      category:"Recently Uploaded",
      thumbnailUrl: "https://img.youtube.com/vi/132kQ6dxPMY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/132kQ6dxPMY?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"indigo biggest hiring,indigo workers,indigo consultants,indigo headquarters,indigo internship,how to go for indigo interview,indigo interview experience recent,",
      channelId: "@OnlineStudy4u",
      channelLogo:"https://yt3.googleusercontent.com/xiQcPdzQL20ytMyd4iCQUVv_2b3TdZhfgNTkSi58IpblqtpNql88kw_F6tocuReEV71S9B-oxuE=s900-c-k-c0x00ffffff-no-rj",
      uploader: "OnlineStudy4u",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment61","userId":"@yashwanthkuruba4751", "text":"I applied from Instagram link.but didn't get any mail update","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video62",
      title: "Accenture Biggest Hiring Finally Out | CGI Hiring | Batch 2024/2024/2023",
      category:"Recently Uploaded",
      thumbnailUrl: "https://img.youtube.com/vi/8BxZJ14_iaY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/8BxZJ14_iaY?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"how to get a job in accenture,how to get a job in accenture bangalore,how to get a job at accenture,how to get job in accenture company,how to get hired in accenture,",
      channelId: "@OnlineStudy4u",
      channelLogo:"https://yt3.googleusercontent.com/xiQcPdzQL20ytMyd4iCQUVv_2b3TdZhfgNTkSi58IpblqtpNql88kw_F6tocuReEV71S9B-oxuE=s900-c-k-c0x00ffffff-no-rj",
      uploader: "OnlineStudy4u",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment62","userId":"@yashwanthkuruba4751", "text":"I applied from Instagram link.but didn't get any mail update","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video63",
      title: "Superset official hiring Phase6 2025/24/23 | Infosys Service Desk Hiring | Deloitte Data Analytics",
      category:"Recently Uploaded",
      thumbnailUrl: "https://img.youtube.com/vi/P7bB_WIREmo/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/P7bB_WIREmo?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"how to get a job in accenture,how to get a job in accenture bangalore,how to get a job at accenture,how to get job in accenture company,how to get hired in accenture,",
      channelId: "@OnlineStudy4u",
      channelLogo:"https://yt3.googleusercontent.com/xiQcPdzQL20ytMyd4iCQUVv_2b3TdZhfgNTkSi58IpblqtpNql88kw_F6tocuReEV71S9B-oxuE=s900-c-k-c0x00ffffff-no-rj",
      uploader: "OnlineStudy4u",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment63","userId":"@yashwanthkuruba4751", "text":"I applied from Instagram link.but didn't get any mail update","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video64",
      title: "🔥Cvent Biggest Hiring 2025, 2024 BATCH | Interview Ongoing | OFF CAMPUS DRIVE FOR 2025, 2024 BATCH",
      category:"Recently Uploaded",
      thumbnailUrl: "https://img.youtube.com/vi/TONyC8-7vbI/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/TONyC8-7vbI?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Hello everyone this video is all about Current Hiring Updates.",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,27,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment54","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video65",
      title: "🔥Wipro Direct Hiring | B.Tech, M.Tech, BCA, MCA, and BSc & Graduates | Daily Drive Ongoing | 2021-25",
      category:"Recently Uploaded",
      thumbnailUrl: "https://img.youtube.com/vi/xz78gOHQvFY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/xz78gOHQvFY?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Hello everyone this video is all about Current Hiring Updates.",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,27,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment65","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video66",
      title: "🔥Wipro Direct Hiring | B.Tech, M.Tech, BCA, MCA, and BSc & Graduates | Daily Drive Ongoing | 2021-25",
      category:"New To You",
      thumbnailUrl: "https://img.youtube.com/vi/xz78gOHQvFY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/xz78gOHQvFY?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Hello everyone this video is all about Current Hiring Updates.",
      channelId: "@LokeshBagora",
      channelLogo:"https://yt3.googleusercontent.com/ytc/AIdro_mKcfGbuVvM12_umvR9AMFKEwXJJ5ifWSgpitiiqDHWyH0=s900-c-k-c0x00ffffff-no-rj",
      uploader: "Online Learning",
      views: "1,27,368 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment66","userId":"@kathivarunraja2084", "text":"Impetus test will be in phases? Also can you tell how many students received the impetus test link? I didn't received the test","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video67",
      title: "Shankar Dada Zindabad Back to back Comedy Scenes 🤣| Chiranjeevi | Telugu Comedy scene",
      category:"New To You",
      thumbnailUrl: "https://img.youtube.com/vi/HQr8S8LTggE/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/HQr8S8LTggE?si=olav7MybyfNvIUZo&autoplay=1&rel=0",
      description:"Explore the official Gemini Comedy channel on YouTube🥳 ! Enjoy Movie Clips , Comedy Scenes, Best scenes, Shorts and more. Subscribe for a cinematic journey into the vibrant world of Telugu cinema!",
      channelId: "@geminicomedy",
      channelLogo:"https://upload.wikimedia.org/wikipedia/commons/1/11/Gemini_Comedy_Logo.png",
      uploader: "Gemini Comedy",
      views: "1,27,38 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment67","userId":"@0000099999ful", "text":"Tiger  comedy  steel  plates tho  inka  brathike  undi  venu maadhav  never  dies  evergreen  😂","timestamp":"3 year ago"}],
    },
    {
      VedioId:  "video68",
      title: "@property Is One Of The Coolest New CSS Features",
      category:"New To You",
      thumbnailUrl: "https://img.youtube.com/vi/sd34qnxSeoU/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/sd34qnxSeoU?autoplay=1&rel=0",
      description:"@property is one of the coolest CSS features that has been released in the last few years. I think it has the potential to be as revolutionary as grid and flexbox, but there are a few tooling changes that need to happen for that first.",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,36,876 views",
      likes: "32k",
      dislikes: "1k",
      comments: [{"commentId": "comment67","userId":"@GilGoldshlager", "text":"terima kasih bang teo akhirnya aku bisa css","timestamp":"1 months ago"}],
    },
    {
      VedioId:  "video69",
      title: "என்னை சொந்தம் Ennai Sondham - Bhediya | Varun Dhawan, Kriti Sanon | Sachin-Jigar",
      category:"New To You",
      thumbnailUrl: "https://img.youtube.com/vi/kZHStsm4jSY/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/kZHStsm4jSY?autoplay=1&rel=0",
      description:"Starring: Varun Dhawan, Kriti Sanon, Deepak Dobriyal, Abhishek Banerjee, Paalin Kabak ",
      channelId:"@zeemusicsouth",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6C9iS5H7mVslUBcWSX-Sdnh3E16ws6V19ROEfeQtjH9rEQcudgFt_jTptPpZfGnpgXo&usqp=CAU",
      uploader:"Zee Music South",
      views: "3,850 views",
      likes: "933k",
      dislikes: "13k",
      comments:[{"commentId": "comment69","userId":"@avenjustortamil8291","text":"Dai Yara neenga enga irundhu da vandhu irukinga Unga YouTube channel la indha Movie oda all Songs Tamil Version Available ah irukku edhuku da original irukkum bodhu thirumbo Release pandinga","timestamp":"2 years ago"}]
    },
    {
      VedioId:  "video70",
      title: "Next.js 15 Ruins Caching Even More",
      category:"New To You",
      thumbnailUrl: "https://img.youtube.com/vi/3RyguimNe8s/maxresdefault.jpg",
  src:"https://www.youtube.com/embed/3RyguimNe8s?autoplay=1&rel=0",
      description:"Caching in Next.js has been a sore subject for a couple years now, but Next.js 15 is here to fix all our caching problems. Well not quite. In reality it fixes a few problems",
      channelId: "@WebDevSimplified",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkmeBlCnSpcRLqIzjBnwfv3lOuDTRDHLY0jQ&s",
      uploader: "Web Dev Simplified",
      views: "1,34,987 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment70","userId":"@incrypted607", "text":"You definitely are one of the people who understand how Nextjs caching mechanisms work.","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video71",
      title: "BILLO J STAR Full Official Audio J STAR Productions",
      category:"Hindi Songs",
      thumbnailUrl: "https://img.youtube.com/vi/vNc7lN-JeWQ/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/vNc7lN-JeWQ?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"One video, four character, one actor. Punjabi singer #Jstar is back with another party anthem #Billo. Put on your dancing shoes and enjoy the dance track of the year.",
      channelId: "@JSTARProductions",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgGluNuqyRJo82mPyH5swVz4xmkVtCMA6twQ&s",
      uploader: "J STAR Productions",
      views: "1,34,987 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment71","userId":"@VeenRanjha", "text":"Party Anthem of The Year 2019 👌👌👌👌👌👌👌👌👌👌👌👌👌👌","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video72",
      title: "DIL TUTDA GAYA || MANI LADLA || Full Official Video || J STAR Productions",
      category:"Hindi Songs",
      thumbnailUrl: "https://img.youtube.com/vi/70qQXx8pmOA/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/70qQXx8pmOA?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"Set BARA MEHSOOS HUNDA - DIL TUTDA GAYA as your caller tune.",
      channelId: "@JSTARProductions",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgGluNuqyRJo82mPyH5swVz4xmkVtCMA6twQ&s",
      uploader: "J STAR Productions",
      views: "1,34,987 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment72","userId":"@VeenRanjha", "text":"Party Anthem of The Year 2019 👌👌👌👌👌👌👌👌👌👌👌👌👌👌","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video73",
      title: "MAARDA || J STAR || J STAR Productions",
      category:"Hindi Songs",
      thumbnailUrl: "https://img.youtube.com/vi/zydvoLVLWTg/maxresdefault.jpg",
      src:"https://www.youtube.com/embed/zydvoLVLWTg?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"Set BARA MEHSOOS HUNDA - DIL TUTDA GAYA as your caller tune.",
      channelId: "@JSTARProductions",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgGluNuqyRJo82mPyH5swVz4xmkVtCMA6twQ&s",
      uploader: "J STAR Productions",
      views: "1,34,987 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment73","userId":"@VeenRanjha", "text":"Party Anthem of The Year 2019 👌👌👌👌👌👌👌👌👌👌👌👌👌👌","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video74",
      title: "J STAR | HULARA | Full Official Music Video | Blockbuster Punjabi Song 2014",
      category:"Hindi Songs",
      thumbnailUrl: "https://img.youtube.com/vi/hmjlQ4vPt4c/hqdefault.jpg",
      src:"https://www.youtube.com/embed/hmjlQ4vPt4c?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"Set BARA MEHSOOS HUNDA - DIL TUTDA GAYA as your caller tune.",
      channelId: "@JSTARProductions",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgGluNuqyRJo82mPyH5swVz4xmkVtCMA6twQ&s",
      uploader: "J STAR Productions",
      views: "1,34,987 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment74","userId":"@VeenRanjha", "text":"Party Anthem of The Year 2019 👌👌👌👌👌👌👌👌👌👌👌👌👌👌","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video75",
      title: "Gabru 2 || J Star || ਗੱਭਰੂ ੨ || Full Official Video || Latest Punjabi Song 2015",
      category:"Hindi Songs",
      thumbnailUrl: "https://img.youtube.com/vi/ES8q0tp6Xu8/hqdefault.jpg",
      src:"https://www.youtube.com/embed/ES8q0tp6Xu8?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"After the WILD SUCCESS of NA NA NA NA multi talented singer Gabru boy J-Star & J Star Productions brings to you “Gabru 2ਗੱਭਰੂ ੨. ENJOY ",
      channelId: "@JSTARProductions",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgGluNuqyRJo82mPyH5swVz4xmkVtCMA6twQ&s",
      uploader: "J STAR Productions",
      views: "1,34,87 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment75","userId":"@VeenRanjha", "text":"J Star Paaji Is Really Back Alwar Live Concert 🔥😍 2023 IV Collab Honey Paaji X J Star Paaji👌","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video76",
      title: "Vidya Vox - Be Free (Pallivaalu Bhadravattakam) ft. Vandana Iyer",
      category:"Indian Pop Music",
      thumbnailUrl: "https://img.youtube.com/vi/eiGdsH1g20k/hqdefault.jpg",
      src:"https://www.youtube.com/embed/eiGdsH1g20k?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"Huge shoutout to Shiji Ulleri for helping shoot the video and coming all the way from Abu Dhabi. Thanks to fam Shankar Tucker for the music production, videography and editing - as usual, its kickass",
      channelId: "@VidyaVox",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQncVGrMwGQlnSAAKl9OsHX8JVVwkCauBi0hQ&s",
      uploader: "Vidya Vox",
      views: "1,34,87 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment76","userId":"@nilahari23", "text":"Matte settante vdo kand vannavar undo??... Ettavum kooduthal ketta malayalam songs ❤️😂","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video77",
      title: "Vidya Vox - Attar Falellaan ft. Devenderpal Singh (Official Video)",
      category:"Indian Pop Music",
      thumbnailUrl: "https://img.youtube.com/vi/-fvaxz-d70s/hqdefault.jpg",
      src:"https://www.youtube.com/embed/-fvaxz-d70s?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"So excited to sing in Punjabi for the first time, hope you love it! Thank you to Devender for always rocking it in every song!",
      channelId: "@VidyaVox",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQncVGrMwGQlnSAAKl9OsHX8JVVwkCauBi0hQ&s",
      uploader: "Vidya Vox",
      views: "1,34,872 views",
      likes: "24k",
      dislikes: "8k",
      comments: [{"commentId": "comment77","userId":"@nilahari23", "text":"Matte settante vdo kand vannavar undo??... Ettavum kooduthal ketta malayalam songs ❤️😂","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video78",
      title: "Vidya Vox - Ello Jogappa (Kannada & English Folk Song Remix)",
      category:"Indian Pop Music",
      thumbnailUrl: "https://img.youtube.com/vi/RDMJWI0pUcE/hqdefault.jpg",
      src:"https://www.youtube.com/embed/RDMJWI0pUcE?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"So excited to sing in Punjabi for the first time, hope you love it! Thank you to Devender for always rocking it in every song!",
      channelId: "@VidyaVox",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQncVGrMwGQlnSAAKl9OsHX8JVVwkCauBi0hQ&s",
      uploader: "Vidya Vox",
      views: "1,34,872 views",
      likes: "29k",
      dislikes: "2k",
      comments: [{"commentId": "comment78","userId":"@nilahari23", "text":"Matte settante vdo kand vannavar undo??... Ettavum kooduthal ketta malayalam songs ❤️😂","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video79",
      title: "Vidya Vox - Fly Away (ft. MaatiBaani) (Official Video)",
      category:"Indian Pop Music",
      thumbnailUrl: "https://img.youtube.com/vi/kQ_A_Q24-hU/hqdefault.jpg",
      src:"https://www.youtube.com/embed/kQ_A_Q24-hU?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"So excited to sing in Punjabi for the first time, hope you love it! Thank you to Devender for always rocking it in every song!",
      channelId: "@VidyaVox",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQncVGrMwGQlnSAAKl9OsHX8JVVwkCauBi0hQ&s",
      uploader: "Vidya Vox",
      views: "1,34,872 views",
      likes: "59k",
      dislikes: "2k",
      comments: [{"commentId": "comment79","userId":"@nilahari23", "text":"Matte settante vdo kand vannavar undo??... Ettavum kooduthal ketta malayalam songs ❤️😂","timestamp":"9 months ago"}],
    },
    {
      VedioId:  "video80",
      title: "Vidya Vox - Vanakkam (Official Video)",
      category:"Indian Pop Music",
      thumbnailUrl: "https://img.youtube.com/vi/uT_z4BZpcZc/hqdefault.jpg",
      src:"https://www.youtube.com/embed/uT_z4BZpcZc?si=hM41j4P7xXdSyMtA&autoplay=1&rel=0",
      description:"So excited to sing in Punjabi for the first time, hope you love it! Thank you to Devender for always rocking it in every song!",
      channelId: "@VidyaVox",
      channelLogo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQncVGrMwGQlnSAAKl9OsHX8JVVwkCauBi0hQ&s",
      uploader: "Vidya Vox",
      views: "1,34,872 views",
      likes: "69k",
      dislikes: "2k",
      comments: [{"commentId": "comment80","userId":"@nilahari23", "text":"Matte settante vdo kand vannavar undo??... Ettavum kooduthal ketta malayalam songs ❤️😂","timestamp":"9 months ago"}],
    },
 ])
console.log("Data Added Successfully")
 }catch(err){
  console.error("Error inserting data:", err);
 }
 });
 const AllData = await Video.find({})

export default AllData
  